### ISSUE TITLE
Cannot grant GET_ACCOUNTS permission

### ISSUE THREAD

**Issue by tontongg** [KazuCocoa/DroidTestHelper#25]
[...]\AppData\Local\Android\sdk\platform-tools>adb shell pm grant com.kazucocoa.droidtesthelper android.permission.GET_ACCOUNTS

Operation not allowed: java.lang.SecurityException: Package com.kazucocoa.droidtesthelper has not requested permission android.permission.GET_ACCOUNTS

I am running app on Android 7.0

Some logs : 

12-06 09:58:37.373 27718-27718/? W/Activity: Can reqeust only one set of permissions at a time
12-06 09:58:37.373 27718-27718/? E/HandleAccountHelper: Can't granted Manifest.permission.GET_ACCOUNTS

**Comment by KazuCocoa** [comment]
Did you run it on a real device?

The following is running on the emulator and in this case granted permission works fine.
Could you check "Permissions" section and see "Contact" permission there?

![image](https://user-images.githubusercontent.com/5511591/33728315-695baf40-dbbd-11e7-8600-183a285e29a5.png)

**Comment by tontongg** [comment]
Yes, real device (honor 5c)
Permissions section in the app info are empty (no Contact permission appear)

**Comment by KazuCocoa** [comment]
I remembered.
Currently, I put the following limitation for Manifest since https://developer.android.com/reference/android/Manifest.permission.html#GET_ACCOUNTS and https://developer.android.com/reference/android/accounts/AccountManager.html .
For 23+, we can't change the data without the same authorised apks because of security.

```
    <uses-permission android:name="android.permission.GET_ACCOUNTS" android:maxSdkVersion="22"/>
    <uses-permission
        android:name="android.permission.MANAGE_ACCOUNTS"
        android:maxSdkVersion="22" />
```

So, this helper all can manage account only for 21-.

**Comment by KazuCocoa** [comment]
If you git clone this repository and generate release api signed the same signature with your test target, I guess you can manage account without grant permissions.

**Comment by tontongg** [comment]
Okay, I understand :) you should update the REAMDE to display this limitation to API lvl 22.
Thank you for taking time to answer me.

**Comment by KazuCocoa** [comment]
Yes, thanks and take a look at this helper!
I'll update it in a few days.

**Comment by KazuCocoa** [comment]
https://github.com/KazuCocoa/DroidTestHelper/blob/master/README.md#remove-account-from-account-manager

**Comment by tqk2811** [comment]
Can root permision work?

**Comment by KazuCocoa** [comment]
I don't know since I haven't tried rooted devices.
